name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          set -e
          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest tag next-release --local --github
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get latest | sed 's/v//g')
          docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version latest
          docker build . --file Dockerfile --tag slack-user-cache
          docker run --rm slack-user-cache /app/slack-user-cache --help
      - name: push to registry
        run: |
          set -e
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get latest | sed 's/v//g')
          docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$(git rev-parse --short HEAD)
          docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$VERSION
          docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:latest
          docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$(git rev-parse --short HEAD)
          docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$VERSION
          docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:latest