name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: login to registry
      run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest tag-version --local --github --ignore-changes
        VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get current-version --no-snapshot | sed 's/v//g')
        docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest update-version --override-version $VERSION
        docker build . --file Dockerfile --tag slack-user-cache
    - name: push to registry
      run: |
        VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get current-version --no-snapshot | sed 's/v//g')
        docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$(git rev-parse --short HEAD)
        docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$VERSION
        docker tag slack-user-cache docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:latest
        docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:$VERSION
        docker push docker.pkg.github.com/ethankhall/slack-user-cache/slack-user-cache:latest